export const EN = {
  "header - total-price": "{{totalPrice}} ₴",

  "logo - title": "React Pizza",
  "logo - description": "the most delicious pizza in the universe",

  "categories - all": "All",
  "categories - meat": "Meat",
  "categories - vegetarian": "Vegetarian",
  "categories - grill": "Grill",
  "categories - spicy": "Spicy",
  "categories - closed": "Closed",

  "sort-popup - sort-by": "Sort by:",
  "sort-popup - popular": "Popular",
  "sort-popup - price": "Price",
  "sort-popup - alphabet": "Alphabet",

  "modal-confirmation - yes": "Yes",
  "modal-confirmation - no": "No",
  "modal-alert - ok": "Ok",

  "pizza-items - no-data": "Data is not loaded or is missing",

  "pizza-card - pepperoni-fresh": "Pepperoni Fresh with pepper",
  "pizza-card - cheese": "Cheese 🌱👶",
  "pizza-card - barbecue-chicken": "Barbecue chicken",
  "pizza-card - sweet-sour-chicken": "Sweet and sour chicken",
  "pizza-card - cheeseburger-pizza": "Cheeseburger-pizza",
  "pizza-card - crazy-pepperoni": "Crazy pepperoni",
  "pizza-card - pepperoni": "Pepperoni",
  "pizza-card - margarita": "Margarita",
  "pizza-card - four-seasons": "Four seasons",
  "pizza-card - vegetables-mushrooms": "Vegetables and mushrooms 🌱",
  "pizza-card - thin": "thin",
  "pizza-card - traditional": "traditional",
  "pizza-card - size": "{{sizeName}} cm.",
  "pizza-card - thin-26": "thin, 26 cm. - {{count}}",
  "pizza-card - thin-30": "thin, 30 cm. - {{count}}",
  "pizza-card - thin-40": "thin, 40 cm. - {{count}}",
  "pizza-card - traditional-26": "traditional, 26 cm. - {{count}}",
  "pizza-card - traditional-30": "traditional, 30 cm. - {{count}}",
  "pizza-card - traditional-40": "traditional, 40 cm. - {{count}}",
  "pizza-card - price": "Price: {{price}} ₴",
  "pizza-card - total-price": "{{totalPrice}} ₴",
  "pizza-card - add": "Add",

  "not-found - title": "Error 404",
  "not-found - description": "Page '{{page}}' not found.",

  "home - all": "All pizzas",
  "home - meat": "Meat pizzas",
  "home - vegetarian": "Vegetarian pizzas",
  "home - grill": "Grill pizzas",
  "home - spicy": "Spicy pizzas",
  "home - closed": "Closed pizzas",

  "cart - title": "Cart",
  "cart - total-price": "Total price: <strong>{{totalPrice}} ₴</strong>",
  "cart - total-count": "Total pizzas: <strong>{{totalCount}} pcs.</strong>",
  "cart - clear-cart": "Clear the cart",
  "cart - clear-modal-title": "Cleaning the cart",
  "cart - clear-modal-text": "Do you want to empty the cart?",
  "cart - order-modal-title": "Order",
  "cart - order-modal-text": "Your order has been accepted! 😋",
  "cart - confirm": "Confirm",
  "cart - decline": "Decline",
  "cart - okay": "Okay",
  "cart - go-back": "Go back",
  "cart - buy": "Buy",

  "empty-cart - title": "Cart is empty 😕",
  "empty-cart - text": `
    <p>You have not added anything to your cart yet.</p>
    <p>To order a pizza, go to the main page!</p>`,
};
