export const UA = {
  "header - total-price": "{{totalPrice}} ₴",

  "logo - title": "React Pizza",
  "logo - description": "найсмачніша піца у Всесвіті",

  "categories - all": "Усі",
  "categories - meat": "М'ясні",
  "categories - vegetarian": "Вегетаріанські",
  "categories - grill": "Гриль",
  "categories - spicy": "Гострі",
  "categories - closed": "Закриті",

  "sort-popup - sort-by": "Сортувати за:",
  "sort-popup - popular": "Популярністю",
  "sort-popup - price": "Ціною",
  "sort-popup - alphabet": "Алфавітом (Eng)",

  "pizza-items - no-data": "Дані не завантажено або вони відсутні",

  "pizza-card - pepperoni-fresh": "Пепероні Фреш з перцем",
  "pizza-card - cheese": "Сирна 🌱👶",
  "pizza-card - barbecue-chicken": "Курча барбекю",
  "pizza-card - sweet-sour-chicken": "Кисло-солодке курча",
  "pizza-card - cheeseburger-pizza": "Чізбургер-піцца",
  "pizza-card - crazy-pepperoni": "Крейзі пеппероні ",
  "pizza-card - pepperoni": "Пеппероні",
  "pizza-card - margarita": "Маргарита",
  "pizza-card - four-seasons": "Чотири сезони",
  "pizza-card - vegetables-mushrooms": "Овочі та гриби 🌱",
  "pizza-card - thin": "тонка",
  "pizza-card - traditional": "традиційна",
  "pizza-card - size": "{{sizeName}} см.",
  "pizza-card - price": "від {{price}} ₴",
  "pizza-card - total-price": "{{totalPrice}} ₴",
  "pizza-card - add": "Додати",

  "not-found - title": "Помилка 404 - Сторінку не знайдено.",

  "home - all": "Усі піци",
  "home - meat": "М'ясні піци",
  "home - vegetarian": "Вегетаріанські піци",
  "home - grill": "Гриль піци",
  "home - spicy": "Гострі піци",
  "home - closed": "Закриті піци",

  "cart - title": "Корзина",
  "cart - total-price": "Сума замовлення: <strong>{{totalPrice}} ₴</strong>",
  "cart - total-count": "Усього піц: <strong>{{totalCount}} шт.</strong>",
  "cart - clear-cart": "Очистити корзину",
  "cart - modal-window-title": "Очищення корзини",
  "cart - modal-window-text": "Ви дійсно хочете очистити корзину?",
  "cart - accept": "Підтвердити",
  "cart - decline": "Відмінити",
  "cart - go-back": "Повернутися назад",
  "cart - pay": "Замовити",
};
